service: crwaler-template

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  stackName: crawler-template
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - '*'
      Resource:
        - '*'
package:
  exclude:
    - '**'
  include:
    - sbi/**
functions:

  crawl:
    handler: crawl_template.crawl_handler
    timeout: 15
    events:
      # クロールしたい時間を記述
      # https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html
      # 以下は平日の10分ごと
      - schedule: cron(0/10 * ? * MON-FRI *)
